export const ERROR_OCCURED = 'ERROR_OCCURED';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';
// export const ERROR_OCCURED = 'ERROR_OCCURED';
// export const ERROR_OCCURED = 'ERROR_OCCURED';
// export const ERROR_OCCURED = ERROR_OCCURED;
// export const ERROR_OCCURED = ERROR_OCCURED;
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REGISTER_USER = 'REGISTER_USER';
